server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: 123456

mybatis:
  type-aliases-package: com.example.demo.dao
  mapper-locations: classpath:mapper/*Mapper.xml
